module.exports = [
  {
    id: 1,
    name: "Notes",
    coverURL: "https://imgur.com/DOKs0aY.png",
    description: "Add Notes...",
    githubURL: "https://github.com/Jubin369/react-nextjs-notes",
    previewURL: "https://react-nextjs-notes.vercel.app/",
    tools: ["Nextjs", "JQuery", "JS", "MongoDb"],
    pinned: true,
  },
  {
    id: 2,
    name: "Rick and Morty ",
    coverURL: "https://imgur.com/2yYGE2Z.png",
    description: "Rick and Morty graphql API...",
    githubURL: "https://github.com/Jubin369/turbolab",
    previewURL: "https://turbolab.vercel.app/",
    tools: ["Reactjs", "Graphql", "Chakra-ui", "Apollo Graphql"],
    pinned: true,
  },
  {
    id: 3,
    name: "Ecommercial-nextjs ",
    coverURL: "https://imgur.com/bgxZZAf.png",
    description: "commercial website home page design.",
    githubURL: "https://github.com/Jubin369/lilac-machine-test",
    previewURL: "http://lilac-interview.vercel.app/",
    tools: ["Nextjs", "Chakra-ui"],
    pinned: true,
  },
];
